compile_pdf:
  stage: build
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make thesis.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - thesis.pdf  # instruct GitLab to keep the main.pdf file
      - introduction.pdf
      - conclusion.pdf
      - detector.pdf
      - theory.pdf
      - machine-learning.pdf
      - results.pdf

pages:
  stage: deploy
  script:
    - mkdir public  # create a folder called public
    - cp thesis.pdf public  # instruct GitLab to keep the main.pdf file
    - cp introduction.pdf public
    - cp conclusion.pdf public
    - cp detector.pdf public
    - cp theory.pdf public
    - cp machine-learning.pdf public
    - cp results.pdf public
  artifacts:
    paths: 
      - public  # instruct GitLab to keep the public folder
  only: 
    - master  # deploy the pdf only for commits made to the master branch 
