compile_thesis:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean thesis.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - thesis.pdf  # instruct GitLab to keep the main.pdf file

compile_intro:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean introduction.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - introduction.pdf  # instruct GitLab to keep the main.pdf file

compile_theoy:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean theory.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - theory.pdf  # instruct GitLab to keep the main.pdf file

compile_detector:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean detector.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - detector.pdf  # instruct GitLab to keep the main.pdf file

compile_ml:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean machine-learning.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - machine-learning.pdf  # instruct GitLab to keep the main.pdf file

compile_reco:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean recon.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - recon.pdf  # instruct GitLab to keep the main.pdf file

compile_modelling:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean modelling.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - modelling.pdf  # instruct GitLab to keep the main.pdf file

compile_fit:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean fit.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - fit.pdf  # instruct GitLab to keep the main.pdf file

compile_results:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean results.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - results.pdf  # instruct GitLab to keep the main.pdf file

compile_conclusion:
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  script: make clean conclusion.pdf  # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - conclusion.pdf  # instruct GitLab to keep the main.pdf file

